# Generated by Django 4.2.5 on 2023-09-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
